export const FETCH_DATA = "SHOPPING_CART/FETCH_DATA";
export const FETCH_SUCCES_DATA = "SHOPPING_CART/FETCH_SUCCES_DATA";
export const REMOVE_ITEM = "SHOPPING_CART/REMOVE_ITEM";
export const UPDATE_CART = "SHOPPING_CART/UPDATE_CART";
export const COMPLETED_CART = "SHOPPING_CART/COMPLETED_CART";
